# /DaSpCoRate/cloudbuild.yaml

steps:
# --- Schritte 1-3 bleiben unverändert ---
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Backend'
  args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/backend:latest', './backend' ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Frontend'
  args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/frontend:latest', '--build-arg', 'VITE_API_URL=${_VITE_API_URL}', './frontend' ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Images'
  args: [ 'push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/backend:latest' ]
- name: 'gcr.io/cloud-builders/docker'
  waitFor: ['Push Images']
  args: [ 'push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/frontend:latest' ]

# --- Schritt 4: Backend auf Cloud Run deployen (Finale Version mit Brevo) ---
- name: 'google/cloud-sdk'
  id: 'Deploy Backend'
  entrypoint: gcloud
  waitFor: ['Push Images']
  args:
    - 'run'
    - 'deploy'
    - 'daspcorate-backend'
    - '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/backend:latest'
    - '--region=europe-west3'
    - '--platform=managed'
    - '--quiet'
    - '--set-cloudsql-instances=${_DB_CONNECTION_NAME}'
    - '--remove-env-vars=DATABASE_URL,MAIL_PASSWORD'
    - '--set-secrets=DATABASE_URL=daspcorate-database-url:latest,MAIL_PASSWORD=brevo-smtp-key:latest'
    - '--update-env-vars=SECRET_KEY=${_SECRET_KEY},ALGORITHM=HS256,ACCESS_TOKEN_EXPIRE_MINUTES=30,MAIL_USERNAME=${_BREVO_USERNAME},MAIL_SERVER=smtp-relay.brevo.com,MAIL_FROM=noreply@danscor.app,FRONTEND_URL=${_FRONTEND_URL}'

# --- Schritt 5: Frontend auf Cloud Run deployen (mit neuem Image) ---
- name: 'google/cloud-sdk'
  id: 'Deploy Frontend'
  entrypoint: gcloud
  waitFor: ['Push Images']
  args:
    - 'run'
    - 'deploy'
    - 'daspcorate-frontend'
    - '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/frontend:latest'
    - '--region=europe-west3'
    - '--platform=managed'
    - '--port=80'
    - '--allow-unauthenticated'
    - '--quiet'

images:
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/backend:latest'
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/daspcorate-repo/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY