# /DaSpCoRate/docker-compose.yml (FINALE VERSION)

services:
  db:
    image: mysql:8.0
    container_name: daspcorate_mysql_db
    env_file:
      - ./.env  # <-- Liest jetzt aus der zentralen Datei
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: daspcorate_backend
    env_file:
      - ./.env  # <-- Liest jetzt auch aus der zentralen Datei
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: daspcorate_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: